import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import './globals.css';


import MuiProvider from '@provider/mui';
import ReduxProvider from '@provider/redux';

const roboto = Roboto({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={roboto.variable}>
				<NextTopLoader />
				<MuiProvider>
					<ReduxProvider>{children}</ReduxProvider>
				</MuiProvider>
			</body>
		</html>
	);
}
